add getallroom and GetById
ShoanRohan/Psagot pull request #10
Opened 2024-12-08 20:01 UTC by michalicoen

2024-12-12 11:05 UTC, tamarbir requested changes
ה PR מצוין, רק הוספתי לך כמה הערות תתקני ותעלי

2024-12-17 10:45 UTC, tamarbir commented on psagot-client/src/features/room/roomActions.js
> +import { createAsyncThunk } from '@reduxjs/toolkit';
רק תמחקי מפה את הקבצים של המשימה השניה (תשמרי אצלך, תדחפי שזה מחוק, ואז תחזירי- בלי לדחוף עדיין)

2024-12-17 10:48 UTC, tamarbir commented
מיכל, דבר ראשון תעשי PULL ניסיתי לסדר לך שם כמה דברים בבראנץ
אחרי זה תמחקי את הקבצים שקשורים למשימת CLIENT 
אחרי זה תקחי גירסה מה teamJ1 , יהיו לך הרבה קונפליקטים, תעזרי במתרגלת לפתור אותן
ואז תדחפי הכל ל GIT אני רוצה לאשר את ה PR שלך....
בהצלחה!

2024-12-17 11:00 UTC, michalicoen commented
דבר ראשון אני לא נותן לי לעשות PULL שנית בקונפליקטים אז יש לי שגיאות
בPROGRAM צירפתי צילום של השגיאות

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-12:48 מאת ‪tamarbir‬‏ <‪
***@***.***‬‏>:‬

> מיכל, דבר ראשון תעשי PULL ניסיתי לסדר לך שם כמה דברים בבראנץ
> אחרי זה תמחקי את הקבצים שקשורים למשימת CLIENT
> אחרי זה תקחי גירסה מה teamJ1 , יהיו לך הרבה קונפליקטים, תעזרי במתרגלת
> לפתור אותן
> ואז תדחפי הכל ל GIT אני רוצה לאשר את ה PR שלך....
> בהצלחה!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShoanRohan/Psagot/pull/10#issuecomment-2548125665>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5VSWRPDU2BF7G7II3F6KE32F76QFAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBYGEZDKNRWGU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-17 11:04 UTC, tamarbir commented
הוא לא צירף את התמונה, אז שימי ב SLACK אני אסתכל מה הבעיה,
את הבעיה ב PROGRAM סידרתי לך תעשי PULL (החבילה AUTO.MAPPER) לא היתה צריכה להיות

2024-12-17 15:40 UTC, michalicoen commented
בסוף מחקתי את התקיה במחשב והורדתי מחדש,
 אני חושבת שזה הסתדר,העלתי לGIT, תעדכני אותי

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-13:04 מאת ‪tamarbir‬‏ <‪
***@***.***‬‏>:‬

> הוא לא צירף את התמונה, אז שימי ב SLACK אני אסתכל מה הבעיה,
> את הבעיה ב PROGRAM סידרתי לך תעשי PULL (החבילה AUTO.MAPPER) לא היתה צריכה
> להיות
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShoanRohan/Psagot/pull/10#issuecomment-2548159521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5VSWRPDDSFTPGNB3OLH5B32GAANJAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBYGE2TSNJSGE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-17 17:04 UTC, tamarbir reviewed
מיכל, כמה דברים קטנים כדי שאני אוכל להכניס את ה PR

2024-12-17 17:04 UTC, tamarbir commented on BL/IRoomBL.cs
> +using System.Text;
לא חושבת שצריך כאן את כל ה using תמחקי מה שלא בשימוש

2024-12-17 17:04 UTC, tamarbir commented on BL/RoomBL.cs
> +
פה תמחקי את השורות המיותרות

2024-12-17 17:04 UTC, tamarbir commented on BL/RoomBL.cs
> +using System.Threading.Tasks;
גם פה לא חושבת שצריך כאן את כל ה using תמחקי מה שלא בשימוש

2024-12-17 17:04 UTC, tamarbir commented on DL/IRoomDL.cs
> +using System.Text;
שוב נראה לי לא נצרך...

2024-12-17 17:04 UTC, tamarbir commented on DL/RoomDL.cs
> +using System.Threading.Tasks;
גם פה מה שלא צריך תמחקי

2024-12-17 17:04 UTC, tamarbir commented on DL/RoomDL.cs
> +    public class RoomDL:IRoomDL
פה יש שורה פעמים, אחת מיותרת

2024-12-17 17:04 UTC, tamarbir commented on psagot-client/src/features/room/roomActions.js
> +import { createAsyncThunk } from '@reduxjs/toolkit';
רק שימי לב לקבצים האלה תשמרי אצלך גיבוי תמחקי ותדחפי לגיט

2024-12-17 17:20 UTC, michalicoen commented
את יכולה לקחת מתמר לגבס עבדנו על זה ביחד,עכשיו אני רואה שיש לי שוב פעם
שגיאות

בתאריך יום ג׳, 17 בדצמ׳ 2024, 19:05, מאת tamarbir ***@***.***
>:

> ***@***.**** commented on this pull request.
>
> מיכל, כמה דברים קטנים כדי שאני אוכל להכניס את ה PR
> ------------------------------
>
> In BL/IRoomBL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888894943>:
>
> > @@ -1,4 +1,10 @@
> -﻿using System.Collections.Generic;
> +﻿using AutoMapper;
> +using DL;
> +using Entities.DTO;
> +using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
>
> לא חושבת שצריך כאן את כל ה using תמחקי מה שלא בשימוש
> ------------------------------
>
> In BL/RoomBL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888895767>:
>
> >
>  namespace BL
>  {
>      public class RoomBL : IRoomBL
> +
>
> פה תמחקי את השורות המיותרות
> ------------------------------
>
> In BL/RoomBL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888896648>:
>
> > @@ -4,11 +4,19 @@
>  using DL;
>  using Entities.DTO;
>  using Entities.Models;
> +using Microsoft.EntityFrameworkCore;
> +using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
>
> גם פה לא חושבת שצריך כאן את כל ה using תמחקי מה שלא בשימוש
> ------------------------------
>
> In DL/IRoomDL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888897326>:
>
> > @@ -1,4 +1,8 @@
> -﻿using System.Collections.Generic;
> +﻿using Entities.Models;
> +using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
>
> שוב נראה לי לא נצרך...
> ------------------------------
>
> In DL/RoomDL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888897849>:
>
> >  using System.Collections.Generic;
>  using System.Threading.Tasks;
>  using Entities.Contexts;
>  using Entities.Models;
>  using Microsoft.EntityFrameworkCore;
> +using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
>
> גם פה מה שלא צריך תמחקי
> ------------------------------
>
> In DL/RoomDL.cs
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888898586>:
>
> >
>  namespace DL
>  {
> +    public class RoomDL:IRoomDL
>
> פה יש שורה פעמים, אחת מיותרת
> ------------------------------
>
> In psagot-client/src/features/room/roomActions.js
> <https://github.com/ShoanRohan/Psagot/pull/10#discussion_r1888900824>:
>
> > @@ -0,0 +1,24 @@
> +import { createAsyncThunk } from ***@***.***/toolkit';
>
> רק שימי לב לקבצים האלה תשמרי אצלך גיבוי תמחקי ותדחפי לגיט
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShoanRohan/Psagot/pull/10#pullrequestreview-2509519156>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5VSWRO5P6TIFESC463YYQ32GBKUXAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBZGUYTSMJVGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-17 17:21 UTC, tamarbir commented
אין בעיות, רק תפתחו PR מהבראנץ שלה

2024-12-17 17:26 UTC, michalicoen commented
בוצע

בתאריך יום ג׳, 17 בדצמ׳ 2024, 19:23, מאת tamarbir ***@***.***
>:

> אין בעיות, רק תפתחו PR מהבראנץ שלה
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShoanRohan/Psagot/pull/10#issuecomment-2549098117>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5VSWRKWYYVPSG4R7Q55B732GBMYTAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBZGA4TQMJRG4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-17 18:23 UTC, michalicoen commented
אני תיקנתי את הבעיות למרות שיש לי שגיאה בROOM אני חושבת שזה משהו לוקאלי
אצלי,אם תוכלי לבדוק בGIT אשמח
תודה רבה

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-17:40 מאת מיכל כהן ***@***.***
‬‏>:‬

> בסוף מחקתי את התקיה במחשב והורדתי מחדש,
>  אני חושבת שזה הסתדר,העלתי לGIT, תעדכני אותי
>
> ‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-13:04 מאת ‪tamarbir‬‏ <‪
> ***@***.***‬‏>:‬
>
>> הוא לא צירף את התמונה, אז שימי ב SLACK אני אסתכל מה הבעיה,
>> את הבעיה ב PROGRAM סידרתי לך תעשי PULL (החבילה AUTO.MAPPER) לא היתה צריכה
>> להיות
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ShoanRohan/Psagot/pull/10#issuecomment-2548159521>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A5VSWRPDDSFTPGNB3OLH5B32GAANJAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBYGE2TSNJSGE>
>> .
>> You are receiving this because you were assigned.Message ID:
>> ***@***.***>
>>
>

2024-12-17 19:19 UTC, michalicoen commented
סליחה שאני משגעת אותך,
 פתרתי את השגיאות שלי והעלתי לGIT

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-20:23 מאת מיכל כהן ***@***.***
‬‏>:‬

> אני תיקנתי את הבעיות למרות שיש לי שגיאה בROOM אני חושבת שזה משהו לוקאלי
> אצלי,אם תוכלי לבדוק בGIT אשמח
> תודה רבה
>
> ‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-17:40 מאת מיכל כהן ***@***.***
> ‬‏>:‬
>
>> בסוף מחקתי את התקיה במחשב והורדתי מחדש,
>>  אני חושבת שזה הסתדר,העלתי לGIT, תעדכני אותי
>>
>> ‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-13:04 מאת ‪tamarbir‬‏ <‪
>> ***@***.***‬‏>:‬
>>
>>> הוא לא צירף את התמונה, אז שימי ב SLACK אני אסתכל מה הבעיה,
>>> את הבעיה ב PROGRAM סידרתי לך תעשי PULL (החבילה AUTO.MAPPER) לא היתה
>>> צריכה להיות
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ShoanRohan/Psagot/pull/10#issuecomment-2548159521>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/A5VSWRPDDSFTPGNB3OLH5B32GAANJAVCNFSM6AAAAABTHQ325WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBYGE2TSNJSGE>
>>> .
>>> You are receiving this because you were assigned.Message ID:
>>> ***@***.***>
>>>
>>

2024-12-17 19:22 UTC, tamarbir reviewed
בעז"ה פעם אחרונה,
תעברי לפני זה על כל הקבצים כדי לוודא שכל השינויים נצרכים, ואין משהו מיותר/חסר בלי סיבה...

2024-12-17 19:22 UTC, tamarbir commented on BL/IRoomBL.cs
שימי לב לכאן להשאיר את מה שהיה (תמחקי שורות מיותרות, ותוסיפי USING שהיה)

2024-12-17 19:22 UTC, tamarbir commented on BL/RoomBL.cs
> +
פה אותו דבר תוסיפי USING שהיה ותמחקי שורות מיותרות

2024-12-17 19:22 UTC, tamarbir commented on BL/RoomBL.cs
> +
גם בקובץ הזה תוסיפי שורות ריקות חסרות, ותמחקי את השורה המיותרת, אין סיבה שיהיה בקובץ הזה שינוי)

2024-12-17 19:22 UTC, tamarbir commented on DL/IRoomDL.cs
> +
שוב כאן אותו דבר להוסיף מה שהיה

2024-12-17 19:22 UTC, tamarbir commented on DL/RoomDL.cs
> +
גם כאן להוסיף, ולמחוק

2024-12-17 19:22 UTC, tamarbir commented on Psagot/Program.cs
>              if (app.Environment.IsDevelopment())
כאן תוסיפי את הערה שנמחקה,

2024-12-17 19:22 UTC, tamarbir commented on psagot-client/src/features/room/roomActions.js
> +import { createAsyncThunk } from '@reduxjs/toolkit';
עדיין הקבצים האלה קיימים לך ב GIT תמחקי ותעלי את הקבצים מחוקים, ככה זה יזהה שהם כבר לא קימים

2024-12-19 10:42 UTC, merged