טבלת 1/User
ShoanRohan/Psagot pull request #11
Opened 2024-12-10 15:09 UTC by Tamar-Kostiner

Add users

2024-12-12 11:07 UTC, tamarbir requested changes

2024-12-15 16:44 UTC, Tamar-Kostiner commented on Entities/Models/Day.cs
> +    public string Descr { get; set; } = null!;
את זה משכתי מאהובה,
אינני יודעת מה היה השינוי,

2024-12-15 16:44 UTC, Tamar-Kostiner commented on Psagot/appsettings.Development.json
> -{
הוא קיים במחשב,
ב-gitignore הוא קיים.

2024-12-15 16:45 UTC, Tamar-Kostiner commented on .gitignore
>  # Fody - auto-generated XML schema
לא נגעתי בקובץ הזה בכלל.
אינני יודעת על איזה שינויים מדובר

2024-12-15 20:13 UTC, merged